### PR TITLE
Throw error when transaction fails

### LINKED ISSUE #1: all the txs are successfull
as our node currently always responds with success on `sendRawTransaction`, this never displays an error:
https://github.com/leapdao/burner-wallet/blob/master/src/App.js#L2038-L2046

### PR DESCRIPTION
**Pull request by TimDaub**
Fixes #1.

Please see the following comment: https://github.com/leapdao/burner-wallet/compare/sunDai...leapdao:fix/display-error-on-invalid-tx?expand=1#diff-14b1e33d5bf5649597cdc0e4f684daddR2109

Currently most send functions still don't throw errors to the user. If we want to fix that, we should follow up on what is described in: https://github.com/austintgriffith/burner-wallet/issues/157

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -2133,7 +2136,49 @@ async function tokenSendV2(from, to, value, color, xdaiweb3, web3, privateKey) {
 
   const signedTx = privateKey ? await transaction.signAll(privateKey) : await transaction.signWeb3(web3);
```
Comment (TimDaub) [inline src/App.js]: If you want to test failing transactions, add the following after this line:

```javascript
signedTx.inputs[0].prevout.hash[signedTx.inputs[0].prevout.hash.length-1] = 0;
```

File: src/App.js [hunk 2]
```diff
@@ -2133,7 +2136,49 @@ async function tokenSendV2(from, to, value, color, xdaiweb3, web3, privateKey) {
...
 
-  return await xdaiweb3.eth.sendSignedTransaction(signedTx.hex())
+  let receipt;
+  try {
+    receipt = await xdaiweb3.eth.sendSignedTransaction(signedTx.hex())
+  } catch(err) {
+      // NOTE: Leap's node currently doesn't implement the "newBlockHeaders"
+      // JSON-RPC call. When a transaction rejected by a node,
```
Comment (TimDaub) [inline src/App.js]:
```suggestion
      // JSON-RPC call. When a transaction is rejected by a node,
```

File: src/App.js [hunk 3]
```diff
@@ -2095,22 +2094,26 @@ async function tokenSend(to, value, gasLimit, txData, cb) {
...
+      xdaiweb3,
+      web3,
+      metaAccount && metaAccount.privateKey
+    )
+  } catch(err) {
+    // NOTE: The callback cb of tokenSend is not used correctly in the expected
+    // format cb(error, receipt) throughout the app. We hence cannot send
+    // errors in the callback :( When no receipt is returned (e.g. null), the
+    // burner wallet will react with not resolving the "sending" view. This is
+    // not ideal and should be changed in the future. We opened a issue on the
```
Comment (TimDaub) [inline src/App.js]:
```suggestion
    // not ideal and should be changed in the future. We opened an issue on the
```

File: src/App.js [hunk 4]
```diff
@@ -2081,37 +2081,43 @@ const isNFT = (color: Number): boolean => color >= NFT_COLOR_BASE;
...
   }
 
-  if(typeof txData == "function"){
+  if(typeof txData === "function"){
     cb = txData
   }
 
   value = xdaiweb3.utils.toWei(""+value, "ether")
   const color = await xdaiweb3.getColor(P_DAI_TOKEN_ADDR);
+  console.log({ account, to, value, color });
```
Comment (TimDaub) [inline src/App.js]: rm
