### PR TITLE
Fix z-index of <Header/>

### LINKED ISSUE #127: Header and QRCodeButton has higher z-index as QRCodeReader
They should not be shown when the camera is open.

Screen Shot 2019-05-20 at 17 54 34

Screen Shot 2019-05-20 at 17 55 03

### PR DESCRIPTION
**Pull request by TimDaub**
Fixes #127

### CODE REVIEW

File: src/components/Header.js [hunk 1]
```diff
@@ -115,7 +115,7 @@ export  default ({openScanner, network, total, ens, address, changeView, view})
 
 
   return (
-    <div className="header" style={{opacity, "z-index": "99"}}>
+    <div className="header" style={{opacity, "z-index": "5"}}>
```
Comment (iamonuwa) [inline src/components/Header.js]: Try using zIndex.

Comment (TimDaub) [reply src/components/Header.js]: Indeed :) Thx, now fixed.
