### PR TITLE
Fix/send eth button in Exchange

### LINKED ISSUE #126: "Send ETH" button from Exchange.js is disabled for Metamask users and needs to be enabled again
Screen Shot 2019-05-20 at 17 52 32

### PR DESCRIPTION
**Pull request by TimDaub**
Fixes #126

TODOs:

- [x] Rebase once #133 is merged into master

### CODE REVIEW

File: src/components/Exchange.js [hunk 1]
```diff
@@ -549,53 +549,104 @@ export default class Exchange extends React.Component {
...
-      this.transferEth(this.state.ethSendToAddress,false,actualEthSendAmount,"Sending $"+this.state.ethSendAmount+" of ETH to "+this.state.ethSendToAddress+"...",()=>{
-        this.props.changeAlert({type: 'success',message: "Sent $"+this.state.ethSendAmount+" of ETH to "+this.state.ethSendToAddress});
+
+      if(gwei !== undefined){
+        if (mainnetMetaAccount) {
+
+          let paramsObject = {
+            from: daiAddress,
+            value: actualEthSendAmount,
+            gas: 240000,
```
Comment (johannbarbie) [inline src/components/Exchange.js]: why such high estimate? the tx only used 21,000 here: https://rinkeby.etherscan.io/tx/0x31c2ce3039741ea64e23adc72af89428c8f3f334159350b1807ff9c8b8d0d6b2

Comment (TimDaub) [reply src/components/Exchange.js]: It's legacy stuff. GasLimits are set arbitrarily like that everywhere. We should actually use `.estimateGas` everywhere.

I'd proceed by leaving it for now and opening an issue upstream. OK?

Comment (TimDaub) [reply src/components/Exchange.js]: https://github.com/austintgriffith/burner-wallet/issues/219
