### PR TITLE
Fix/upstream master rebase

### LINKED ISSUE #114: Rebase latest updates from upstream into master
## Scope

- Master is currently 38 commits ahead. Rebase these changes and make sure everything still works.

## Deliverables

- A PR that features all upstream changes and brings our master up to date.

## Gain for the project

- In my limited XP it's better to rebase regularly when maintaining a fork

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: @TimDaub  / 75%
bounty reviewer: @johannbarbie  / 15%

### PR DESCRIPTION
**Pull request by TimDaub**
Screen Shot 2019-05-17 at 14 11 39

Didn't test much. I think we can do that when we rebase against cinemarket.
Notable features added from upstream:

- Incognito detection: When in incognito mode, burner-wallet displays state.
- Allows to withdraw ERC721s in WithdrawFromPrivate. Not sure we need that functionality. Please discuss. IMO we don't need it.

Fixes #114

### CODE REVIEW

File: src/components/Receive.js [hunk 1]
```diff
@@ -38,6 +38,12 @@ export default class Receive extends React.Component {
               </div>
             </div>
           </CopyToClipboard>
+          <div style={{width:"100%",textAlign:'center',padding:20}}>
+            <a href={"https://blockscout.com/poa/dai/address/"+address+"/transactions"} target="_blank">
```
Comment (TimDaub) [inline src/components/Receive.js]: ups. I'll change to testnet for now

File: src/components/WithdrawFromPrivate.js [hunk 2]
```diff
@@ -43,6 +48,43 @@ export default class SendToAddress extends React.Component {
   }
 
   async poll(){
+
+    if(this.props.contracts && this.props.contracts.Badges){
```
Comment (TimDaub) [inline src/components/WithdrawFromPrivate.js]: As far as I understand, the following lines in this file do the following:

They allow to withdraw badges when scanning a private key. Do we really need that functionality? I'd say no. I imagine it could cause problems when we withdraw.

File: src/App.js [hunk 3]
```diff
@@ -568,9 +611,14 @@ class App extends Component {
         console.log("this.state.xdaiBalance",this.state.xdaiBalance)
         console.log("this.state.daiBalance",this.state.daiBalance)
         console.log("this.state.isVendor",this.state.isVendor)
+        console.log("this.state.badges",this.state.badges)
+        let badgeCount = 0
+        for(let b in this.state.badges){
```
Comment (TimDaub) [inline src/App.js]: Thinking of replacing this with `let badgeCount = this.state.badges.length`

File: src/components/Balance.js [hunk 4]
```diff
@@ -18,10 +18,23 @@ export  default ({icon, text, selected, amount, address, dollarDisplay}) => {
     opacity=0.05
   }
 
+  let iconDisplay
+
+    if(typeof icon == "string" && icon.length<8){
```
Comment (TimDaub) [inline src/components/Balance.js]: Indentation

File: src/App.js [hunk 5]
```diff
@@ -525,6 +559,7 @@ class App extends Component {
           }
         }catch(e){
           console.log(e)
+          this.connectToRPC()
```
Comment (TimDaub) [inline src/App.js]: 🤔

File: src/components/Exchange.js [hunk 6]
```diff
@@ -704,56 +704,6 @@ export default class Exchange extends React.Component {
       console.log("ERRORed RESPONSE FROM ethgasstation",response)
     }
   }
-  sendXdai(){
```
Comment (TimDaub) [inline src/components/Exchange.js]: Not sure if that was my fault or if it was simply deleted.

File: src/components/SendByScan.js [hunk 7]
```diff
@@ -259,7 +259,7 @@ class SendByScan extends Component {
         </div>
         {displayedReader}
         <div style={{position: 'absolute',zIndex:11,bottom:20,fontSize:12,left:20,color:"#FFFFFF",opacity:0.333}}>
-          {navigator.userAgent} - {JSON.stringify(navigator.mediaDevices)}
+          {window.navigator.userAgent} - {JSON.stringify(window.navigator.mediaDevices)}
```
Comment (TimDaub) [inline src/components/SendByScan.js]: 🤷‍♂

File: src/components/WithdrawFromPrivate.js (hunk 2 above)
Comment (TimDaub) [reply src/components/WithdrawFromPrivate.js]: I reverted the whole thing in 9dca25d and 27218d7. Lemme know if we should leave it in...

Comment (johannbarbie) [reply src/components/WithdrawFromPrivate.js]: good question.
if we would have a scavenger hunt like game, it would be useful, you could hide qr codes around city, and people would swipe them. that is all i can think of :)

Comment (TimDaub) [reply src/components/WithdrawFromPrivate.js]: OK, but then it's not relevant yet for the current plan that we have with the burner-wallet. We can always re-revert those commits.

**Comment by TimDaub** [comment]
> 🚳 transfer receipt (expected?)

Yeah,

```
Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.
```

Should be fixed when I rebase against cinemarket branch.

**Comment by TimDaub** [comment]
> Should be fixed when I rebase against cinemarket branch.

It is.
