### PR TITLE
Fix transaction history

### LINKED ISSUE #2: merchants need working txs history
from xdai.io
Screen Shot 2019-04-04 at 12 21 19 PM

### PR DESCRIPTION
**Pull request by TimDaub**
This fixes #2 the transaction history for both a browser with Metamask account and without.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -386,7 +386,8 @@ class App extends Component {
     intervalLong = setInterval(this.longPoll.bind(this),45000)
     setTimeout(this.longPoll.bind(this),150)
 
-    let mainnetweb3 = new Web3(new Web3.providers.WebsocketProvider(WEB3_PROVIDER));
+    // NOTE: Change this to mainnet again when ready for mainnet launch.
+    let mainnetweb3 = new Web3(new Web3.providers.WebsocketProvider("wss://rinkeby.infura.io/ws/v3/e0ea6e73570246bbb3d4bd042c4b5dac"));
```
Comment (sunify) [inline src/App.js]: Shouldn't a color for deposit changed as well?

https://github.com/leapdao/burner-wallet/blob/pdai-transaction-history/src/components/Exchange.js#L536
https://github.com/leapdao/burner-wallet/blob/pdai-transaction-history/src/components/Exchange.js#L569

Comment (johannbarbie) [reply src/App.js]: i had put color 1 when working on testnet zeta. Tim has found the error later and then changed here: https://github.com/leapdao/burner-wallet/pull/12

Comment (johannbarbie) [reply src/App.js]: i guess the color should be ideally a config param for the app, right? :)
